FinalProject/FinalProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('lessons/', include('projects.urls')),
    path('', include('users.urls')),
    path('quizes/', include('quizes.urls', namespace='quizes')),
    path('results/', include('results.urls', namespace='results')),
]
# URL pattern to have access to the static files in the web application (images)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FinalProject/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns =[
    path('', views.projects, name="projects"),
    path('project/<str:pk>/', views.project, name="project"),
    path('create-module/', views.createProject, name="create-project"),
    path('update-project/<str:pk>', views.updateProject, name="update-project"),
    path('delete-project/<str:pk>', views.deleteProject, name="delete-project"),
    path('create-lesson/', views.createLesson, name='create-lesson'),
    path('update_current_module/', views.update_current_module, name='update_current_module'),
]

FinalProject/quizes/urls.py
from django.urls import path
from .views import (
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
    get_incorrect_questions,
    update_current_quiz,
    create_quiz,
    add_question
)

app_name = 'quizes'

urlpatterns=[
    path('update_current_quiz/', update_current_quiz, name='update_current_quiz'),
    path('create-quiz/', create_quiz, name="create-quiz"),
    path('add-question/', add_question, name="add-question"),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),
    path('<pk>/get_incorrect_questions/', get_incorrect_questions, name='incorrect-questions-view'),
]

FinalProject/results/urls.py
from django.urls import path
from .views import (
    leaderboard,
)

app_name = 'results'

urlpatterns=[
    path('leaderboard/', leaderboard, name='leaderboard'),
]

FinalProject/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('', views.registerUser, name="register"),
    path('profiles/', views.profiles, name="profiles"),
    path('profile/', views.userProfile, name="user-profile"),
    path('profile/<uuid:pk>/', views.adminUserProfile, name="admin-user-profile"),
    path('update_user/', views.update_user, name='update_user'),
]

FinalProject/templates/footer.html
<footer class="bg-light text-center text-lg-start">
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2023 Copyright:
      <a class="text-dark" href="https://mdbootstrap.com/">CryptoPRO.com</a>
    </div>
</footer>

FinalProject/templates/main.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title>CryptoPRO</title>
    <link rel="stylesheet" type="text/css" media="screen" href='{% static "styles/main.css" %}'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
    
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqN5MOkzb+Q0KXy0Fk2zdzeH5np9+0sTv9KG5hZpka2u4sE3zU2E+1B8U" crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-Ts4hxfn6p3G8RGSeJ1BfVqkkSQpfQ42DgcL/8+0xQfrJ2ApeIebmLGzPzIr0jAMq" crossorigin="anonymous"></script>


    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <title>Crypto PRO | {% block title %}{% endblock title %}</title>
</head>
<style>
    .not-visible{
        display: none;
    }
</style>
<body>
    {%  include 'navbar.html' %}

    {% if messages %}
    <!-- <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</li>
        {% endfor %}
    </ul> -->
    {% endif %}

    {% block content %}

    {%  endblock content %}

    {% block scripts %}
    {% endblock scripts %}

    {% include 'footer.html' %}
    
</body>
</html>

FinalProject/templates/navbar.html
{% load static %}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    {% if request.user.is_authenticated %}
    <a class="navbar-brand me-2" href="{% url 'projects:projects' %}">
      <img
        src="{% static 'images/logo.svg'%}"
        height="30"
        alt="MDB Logo"
        loading="lazy"
        style="margin-top: -1px;"
      />
      CryptoPRO
    </a>
    {% else %}
      <span class="navbar-brand me-2">
          <img
              src="{% static 'images/logo.svg'%}"
              height="30"
              alt="MDB Logo"
              loading="lazy"
              style="margin-top: -1px; pointer-events: none; opacity: 0.5;"
          />
          CryptoPRO
      </span>
    {% endif %}


    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if request.user.is_authenticated %}
        {% if request.user.is_staff == False  %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user-profile' %}">Profile</a>
        </li>
        {% endif %}
        {% if request.user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profiles' %}">Users</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'projects:projects' %}">Modules</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'results:leaderboard' %}">Leaderboard</a>
        </li>
        {% if request.user.is_staff %}
          <!-- Display "Add Lesson" link only if the user is an admin -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projects:create-project' %}">Add Module</a>
          </li>
        {% endif %}
        {% if request.user.is_staff %}
          <!-- Display "Add Lesson" link only if the user is an admin -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projects:create-lesson' %}">Add Lesson</a>
          </li>
        {% endif %}
        {% if request.user.is_staff %}
          <!-- Display "Add Lesson" link only if the user is an admin -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'quizes:create-quiz' %}">Add Quiz</a>
          </li>
        {% endif %}
        {% if request.user.is_staff %}
          <!-- Display "Add Lesson" link only if the user is an admin -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'quizes:add-question' %}">Add Question</a>
          </li>
        {% endif %}
        {% endif %}
      </ul>
      <!-- Left links -->

      <div class="d-flex align-items-center">
        {% if request.user.is_authenticated %}
        <button type="button" class="btn btn-primary me-3">
          <a href="{% url 'logout' %}" class="custom-link">Logout</a>
        </button>
        {% else %}
        <button type="button" class="btn btn-primary me-3">
          <a href="{% url 'login' %}" class="custom-link">Login/Register</a>
        </button>
        {% endif %}
        
      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

<style>
  .custom-link {
    color: white;
    text-decoration: none;
  }
</style>