FinalProject/FinalProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('lessons/', include('projects.urls')),
    path('', include('users.urls')),
    path('quizes/', include('quizes.urls', namespace='quizes')),
    path('results/', include('results.urls', namespace='results')),
]
# URL pattern to have access to the static files in the web application (images)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FinalProject/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns =[
    path('', views.projects, name="projects"),
    path('project/<str:pk>/', views.project, name="project"),
    path('create-module/', views.createProject, name="create-project"),
    path('update-project/<str:pk>', views.updateProject, name="update-project"),
    path('delete-project/<str:pk>', views.deleteProject, name="delete-project"),
    path('create-lesson/', views.createLesson, name='create-lesson'),
    path('update_current_module/', views.update_current_module, name='update_current_module'),
]

FinalProject/quizes/urls.py
from django.urls import path
from .views import (
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
    get_incorrect_questions,
    update_current_quiz,
    create_quiz,
    add_question
)

app_name = 'quizes'

urlpatterns=[
    path('update_current_quiz/', update_current_quiz, name='update_current_quiz'),
    path('create-quiz/', create_quiz, name="create-quiz"),
    path('add-question/', add_question, name="add-question"),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),
    path('<pk>/get_incorrect_questions/', get_incorrect_questions, name='incorrect-questions-view'),
]

FinalProject/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('', views.registerUser, name="register"),
    path('profiles/', views.profiles, name="profiles"),
    path('profile/', views.userProfile, name="user-profile"),
    path('profile/<uuid:pk>/', views.adminUserProfile, name="admin-user-profile"),
    path('update_user/', views.update_user, name='update_user'),
]

FinalProject/projects/models.py
from django.db import models
import uuid
# Create your models here.



class Project(models.Model):
    title = models.CharField(max_length=200)
    number = models.IntegerField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title
    
class Lesson(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    number = models.IntegerField(null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    project = models.ForeignKey(Project, related_name='lessons', on_delete=models.CASCADE, default='8fd8d246-8b97-439b-8291-9f85fb156483')

    def __str__(self):
        return self.title
    
    def get_sections(self):
        return self.sections.all()

class LessonSection(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='sections')
    title = models.CharField(max_length=200)
    content = models.TextField(null=True, blank=True)
    ordered_list = models.TextField(null=True, blank=True)
    term_definition = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='lesson_images/', default="profiles/defaultprofile.jpeg")

    def __str__(self):
        return self.title
    
    def get_ordered_list_as_list(self):
        if self.ordered_list:
            return self.ordered_list.splitlines()
        return []

FinalProject/quizes/models.py
from django.db import models
from projects.models import Project

# Create your models here.

DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard')
)

class Quiz(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='quizzes', default='8fd8d246-8b97-439b-8291-9f85fb156483')
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    required_score_to_pass = models.IntegerField(help_text="required score in %")
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)
    max_points = models.IntegerField(default=10)

    def __str__(self):
        return f"{self.name}-{self.topic}"
    
    def get_questions(self):
        return self.question_set.all()[:self.number_of_questions]
    
    def calculate_max_score(self):
        if self.difficulty == 'easy':
            return self.max_points
        elif self.difficulty == 'medium':
            return self.max_points * 2
        elif self.difficulty == 'hard':
            return self.max_points * 3
        
    def save(self, *args, **kwargs):
        # Calculate and set max_score before saving the object
        self.max_score = self.calculate_max_score()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Quizes'

FinalProject/quizes/forms.py
from django.forms import ModelForm
from .models import Quiz
from questions.models import Question, Answer

class QuizForm(ModelForm):
    class Meta:
        model = Quiz
        fields = ['project', 'name', 'topic', 'number_of_questions', 'time', 'required_score_to_pass', 'difficulty']

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['text', 'quiz', 'lesson']


class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'correct', 'question']

FinalProject/quizes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.forms import inlineformset_factory

import random

from questions.models import Question, Answer, IncorrectQuestion
from results.models import Result
from users.models import Profile
from results.views import update_leaderboard

from .forms import QuizForm, QuestionForm, AnswerForm



class QuizListView(ListView):
    model = Quiz
    template_name = 'quizes/quizes.html'

# Function to retrieve a specific quiz based on its 'pk'
def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})

#Function to return JSON data containing info about the quiz:
# Questions with their possible answers
def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append({'text': a.text, 'correct': a.correct})
        questions.append({str(q): answers})
    print("Original Questions Data: ", questions)
    return JsonResponse({
        'data': questions,
        'quiz_name': quiz.name,
        'r_score': quiz.required_score_to_pass,
    })

@csrf_exempt
def save_quiz_view(request, pk):
    # Check if the request is an AJAX request
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        questions = []
        data = request.POST
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')
        
        # Retrieving the questions of the quiz
        for k in data_.keys():
            print('key: ', k)
            try:
                question = Question.objects.get(text=k)
                questions.append(question)
            except Question.DoesNotExist:
                print('Question not found: ', k)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        incorrect_questions = [] # List to store incorrectly answered questions

        # Loop through each question
        for q in questions:
            a_selected = request.POST.get(q.text)
            
            # Check if an answer was selected
            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                correct_answer = None # Initialize correct_answer variable
                
                # Loop through all the answers
                for a in question_answers:
                    # Match the selected answer to the answers available
                    if a_selected == a.text:
                        # Check if the selected answer was correct
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                        else:
                            # Check if the question is not already in the list of incorrect questions
                            if not any(item['question'] == q for item in incorrect_questions):
                                incorrect_question_instance = IncorrectQuestion.objects.filter(user=user, quiz=quiz, question=q).first()
                                # Check if the question is not already in the database
                                if not incorrect_question_instance:
                                    # Save the incorrect answers
                                    incorrect_questions.append({
                                        'question': q,
                                        'frequency': 1,
                                    })
                                    print("Just added a new incorrect question to the database!")
                                else:
                                    incorrect_question_instance.frequency += 1
                                    incorrect_question_instance.save()
                                    print("Just incremented the frequency of one of the previously incorrect questions!")

                    else:
                        if a.correct:
                            correct_answer = a.text
                print("Incorrect answers: ", incorrect_questions)
                # Results will hold The Question itself, the correct answer, and the answer I selected
                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})

        score_ = score * multiplier
        # Create a Result object for the user's quiz attempt
        result_instance = Result.objects.create(quiz=quiz, user=user, score=score_) 

        # Save incorrect answers in the IncorrectAnswer model
        for incorrect_question in incorrect_questions:
            IncorrectQuestion.objects.create(
                user=user,
                quiz=quiz,
                question=incorrect_question['question'],
                frequency=incorrect_question['frequency']
            )

        update_leaderboard(request.user) 

        # Return JSON response indicating whether the quiz was passed. the score, and detailed results
        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})
        


@csrf_exempt
def get_incorrect_questions(request, pk):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        # Retrieve all incorrect questions
        incorrect_questions = IncorrectQuestion.objects.filter(user=request.user)

        # Randomly select 2 questions
        random_questions = random.sample(list(incorrect_questions), min(2, len(incorrect_questions)))

        # Prepare data for JSON response
        questions_data = []
        for question in random_questions:
            question_data = {str(question.question): []}
            for answer in question.question.get_answers():
                question_data[str(question.question)].append({
                    'text': answer.text,
                    'correct': answer.correct
                })
            questions_data.append(question_data)
        print("Incorrect Questions Data: ", questions_data)
        return JsonResponse({'data': questions_data})
    else:
        pass


@csrf_exempt
def update_current_quiz(request):
    if request.method == 'POST':
        quiz_title = request.POST.get('quiz_title', '')
        try:
            profile_obj = Profile.objects.get(user=request.user)
            profile_obj.current_quiz = quiz_title
            print("Current quiz was just changed in the back end! Changed to: ", profile_obj.current_quiz)
            profile_obj.save()
            return JsonResponse({'success': True})
        except Profile.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Profile not found'})
    return JsonResponse({'success': False, 'error': 'Invalid request'})

@login_required(login_url="login")
def create_quiz(request):
    quiz_form = QuizForm()
    if request.method == 'POST':
        quiz_form = QuizForm(request.POST, request.FILES)
        if quiz_form.is_valid():
            quiz_form.save()
            return redirect('projects:projects')
    context = {
        'quiz_form':quiz_form,
    }
    return render(request, 'quizes/create_quiz.html', context)

@login_required(login_url="login")
def add_question(request):
    AnswerFormSet = inlineformset_factory(Question, Answer, form=AnswerForm, extra=3)

    if request.method == 'POST':
        question_form = QuestionForm(request.POST)
        answer_formset = AnswerFormSet(request.POST)

        if question_form.is_valid() and answer_formset.is_valid():
            question = question_form.save()
            answer_formset.instance = question
            answer_formset.save()
            return redirect('projects:projects')
    else:
        question_form = QuestionForm()
        answer_formset = AnswerFormSet()

    context = {
        'question_form': question_form,
        'answer_formset': answer_formset,
    }
    return render(request, 'quizes/add_question.html', context)

FinalProject/quizes/templates/quizes/add_question.html
{% extends 'main.html' %}

{% block content %}



<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center mb-4">Add a new Quiz for the Module</h2>

            <form method="post">
                {% csrf_token %}
                <!-- Question Form -->
                <div class="form-group">
                    <label for="id_question_text">Quiz:</label>
                    {{ question_form.quiz }}
                </div>
                <div class="form-group">
                    <label for="id_question_text">Question:</label>
                    {{ question_form.text }}
                </div>
                <div class="form-group">
                    <label for="id_lesson">Lesson:</label>
                    {{ question_form.lesson }}
                </div>
                <!-- Answer Formset -->
                {{ answer_formset.management_form }}
                {% for form in answer_formset %}
                <div class="form-group">
                    <label for="id_form-{{ forloop.counter0 }}-text">Answer {{ forloop.counter }}:</label>
                    {{ form.text }}
                </div>
                <div class="form-group">
                    <label for="id_form-{{ forloop.counter0 }}-correct">Correct:</label>
                    {{ form.correct }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

FinalProject/quizes/templates/quizes/create_quiz.html
{% extends 'main.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center mb-4">Add a new Quiz for the Module</h2>

            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    {{ quiz_form.project.label_tag }}
                    {{ quiz_form.project }}
                </div>
                <div class="form-group">
                    {{ quiz_form.name.label_tag }}
                    {{ quiz_form.name}}
                </div>
                <div class="form-group">
                    {{ quiz_form.topic.label_tag }}
                    {{ quiz_form.topic }}
                </div>
                <div class="form-group">
                    {{ quiz_form.number_of_questions.label_tag }}
                    {{ quiz_form.number_of_questions }}
                </div>
                <div class="form-group">
                    {{ quiz_form.time.label_tag }}
                    {{ quiz_form.time }}
                </div>
                <div class="form-group">
                    {{ quiz_form.required_score_to_pass.label_tag }}
                    {{ quiz_form.required_score_to_pass }}
                </div>
                <div class="form-group">
                    {{ quiz_form.difficulty.label_tag }}
                    {{ quiz_form.difficulty }}
                </div>
                <button type="submit" class="btn btn-primary btn-block mb-2">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

FinalProject/quizes/templates/quizes/leaderboard.html
{% extends "main.html" %}
{% load static %}

{% block content %}
<style>
    /* Add this to your stylesheet or within a <style> block in your HTML file */
    .podium {
    display: flex;
    justify-content: space-around;
    margin-bottom: 20px;
    }

    .podium-item {
    width: 30vh;
    height: 30vh;
    border-radius: 50%;
    text-align: center;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    font-weight: bold;
    }

    .gold {
    background-color: gold;
    }

    .silver {
    background-color: silver;
    }

    .bronze {
    background-color: #cd7f32;
    }

    .place {
    font-size: 1.5em;
    margin-bottom: 5px;
    }

    .leaderboard-list {
    list-style-type: none;
    padding: 0;
    }

    .leaderboard-item {
    margin-bottom: 10px;
    margin-left: 10px;
    margin-right: 10 px;
    background-color: #f2f2f2;
    padding: 10px;
    border-radius: 5px;
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
    }

    .username {
    font-size: 1.2em;
    font-weight: bold;
    }

    .points {
    font-size: 1.2em;
    }

    .profile-pic {
    width: 100px;  /* Adjust the size as needed */
    height: 100px;  /* Adjust the size as needed */
    object-fit: cover;
    border-radius: 50%;
    margin-bottom: 10px;
    }

    .highlighted {
        border: 10px solid #076aff;  /* Set your preferred highlight color */
        border-radius: 50%;  /* To make the border circular */
    }

    .highlighted-li {
      background-color: #076aff;
    }

</style>

<h2 class="ml-4 mb-5 mt-2">Leaderboard</h2>
<div class="podium">
  <div class="podium-item  gold mb-5 {% if user.is_authenticated and leaderboard_data.0 and user == leaderboard_data.0.user %} highlighted {% endif %}">
    <span class="place">1st</span>
    {% if leaderboard_data.0 %}
      <img src="{{ leaderboard_data.0.user.profile.profile_image.url }}"alt="User1" class="profile-pic img-fluid">
      <span class="username">{{ leaderboard_data.0.user.profile.name }}</span>
      <span class="points">{{ leaderboard_data.0.user.profile.points_of_progress }} XP</span>
    {% endif %}
  </div>
  <div class="podium-item  silver mb-5 {% if user.is_authenticated and leaderboard_data.1 and user == leaderboard_data.1.user %} highlighted {% endif %}">
    <span class="place">2nd</span>
    {% if leaderboard_data.1 %}
      <img src="{{ leaderboard_data.1.user.profile.profile_image.url }}"alt="User2" class="profile-pic img-fluid">
      <span class="username">{{ leaderboard_data.1.user.profile.name }}</span>
      <span class="points">{{ leaderboard_data.1.user.profile.points_of_progress }} XP</span>
    {% endif %}
  </div>
  <div class="podium-item  bronze mb-5 {% if user.is_authenticated and leaderboard_data.2 and user == leaderboard_data.2.user %} highlighted {% endif %}">
    <span class="place">3rd</span>
    {% if leaderboard_data.2 %}
      <img src="{{ leaderboard_data.2.user.profile.profile_image.url }}"alt="User3" class="profile-pic img-fluid">
      <span class="username">{{ leaderboard_data.2.user.profile.name }}</span>
      <span class="points">{{ leaderboard_data.2.user.profile.points_of_progress }} XP</span>
    {% endif %}
  </div>
</div>
<ol class="leaderboard-list">
  {% for result in leaderboard_data|slice:"3:" %}
    <li class="leaderboard-item ml-4 mr-4 {% if user.is_authenticated and user == result.user %} highlighted-li {% endif %}">
      <span class="place">{{ forloop.counter0|add:"4" }}</span>
      <span class="username">{{ result.user.profile.name }}</span>
      <span class="points">{{ result.user.profile.points_of_progress }} XP</span>
    </li>
  {% endfor %}
</ol>
{% endblock content %}

FinalProject/quizes/templates/quizes/quiz.html
{% extends "main.html" %}
{% load static %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}
<style>
    /* Style for quiz questions */
    .quiz-question {
      margin-top: 20px;
      margin-bottom: 10px;
      font-weight: bold;
      font-size: 18px;
      margin-left: 10px;
    }
  
    /* Style for quiz answers */
    .quiz-answer {
      margin-bottom: 5px;
      margin-left: 10px;
    }
  
    /* Style for radio buttons and labels */
    .ans {
      margin-right: 5px;
      margin-left: 10px;
    }

    .question-progress {
      font-size: 16px;
      font-weight: bold;
      margin-bottom: 10px;
    }

    .quiz-container {
      display: flex;
      flex-direction: column;
      align-items: center;
      text-align: center;
    }

    .quiz-answers{
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    .correct-feedback {
      color: green;
      font-weight: bold;
      margin-top: 10px;
      margin-left: 15px;
    }

    .incorrect-feedback {
      color: red;
      font-weight: bold;
      margin-top: 10px;
      margin-left: 15px;
    }

  
    /* Additional styling if needed */
  </style>
<b class="ml-3 h4">{{obj.name}}</b>
<p class="ml-3">Score to pass: {{obj.required_score_to_pass}}%</p>
<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <!-- <button type="submit">Submit</button> -->
</form>
<div class="ml-3 mb-4" id="score-box"></div>
<div id="result-box"></div>
<div id="end-box"></div>
<a class="btn btn-primary mt-3 ml-3 mb-3" id="congratulations-button" href="{% url 'projects:projects' %}" style="display: none;">Back to the modules</a> 
{% endblock content %}

{% block scripts %}
    <script src="{% static 'quizes/quiz.js' %}" defer></script>
{% endblock scripts %}

FinalProject/quizes/templates/quizes/quizes.html
<!-- {% extends "main.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}

  <div class="modal fade" id="quizStartModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="modal-body-confirm"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
          <button type="button" id="start-button" class="btn btn-success">Yes</button>
        </div>
      </div>
    </div>
  </div>

  <div class="h1">Quiz List</div>
  <hr>
  {% for obj in object_list %}
    <button
        class="btn btn-link modal-button"
        data-pk="{{obj.pk}}"
        data-quiz="{{obj.name}}"
        data-questions="{{obj.number_of_questions}}"
        data-difficulty="{{obj.difficulty}}"
        data-time="{{obj.time}}"
        data-pass="{{obj.required_score_to_pass}}"
        data-toggle="modal"
        data-target="#quizStartModal"
    >{{obj.name}}</button><br>
  {% endfor %}
{% endblock content %} -->