FinalProject/FinalProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('lessons/', include('projects.urls')),
    path('', include('users.urls')),
    path('quizes/', include('quizes.urls', namespace='quizes')),
    path('results/', include('results.urls', namespace='results')),
]
# URL pattern to have access to the static files in the web application (images)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FinalProject/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns =[
    path('', views.projects, name="projects"),
    path('project/<str:pk>/', views.project, name="project"),
    path('create-module/', views.createProject, name="create-project"),
    path('update-project/<str:pk>', views.updateProject, name="update-project"),
    path('delete-project/<str:pk>', views.deleteProject, name="delete-project"),
    path('create-lesson/', views.createLesson, name='create-lesson'),
    path('update_current_module/', views.update_current_module, name='update_current_module'),
]

FinalProject/quizes/urls.py
from django.urls import path
from .views import (
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
    get_incorrect_questions,
    update_current_quiz,
    create_quiz,
    add_question
)

app_name = 'quizes'

urlpatterns=[
    path('update_current_quiz/', update_current_quiz, name='update_current_quiz'),
    path('create-quiz/', create_quiz, name="create-quiz"),
    path('add-question/', add_question, name="add-question"),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),
    path('<pk>/get_incorrect_questions/', get_incorrect_questions, name='incorrect-questions-view'),
]

FinalProject/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('', views.registerUser, name="register"),
    path('profiles/', views.profiles, name="profiles"),
    path('profile/', views.userProfile, name="user-profile"),
    path('profile/<uuid:pk>/', views.adminUserProfile, name="admin-user-profile"),
    path('update_user/', views.update_user, name='update_user'),
]

FinalProject/projects/models.py
from django.db import models
import uuid
# Create your models here.



class Project(models.Model):
    title = models.CharField(max_length=200)
    number = models.IntegerField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title
    
class Lesson(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    number = models.IntegerField(null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    project = models.ForeignKey(Project, related_name='lessons', on_delete=models.CASCADE, default='8fd8d246-8b97-439b-8291-9f85fb156483')

    def __str__(self):
        return self.title
    
    def get_sections(self):
        return self.sections.all()

class LessonSection(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='sections')
    title = models.CharField(max_length=200)
    content = models.TextField(null=True, blank=True)
    ordered_list = models.TextField(null=True, blank=True)
    term_definition = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='lesson_images/', default="profiles/defaultprofile.jpeg")

    def __str__(self):
        return self.title
    
    def get_ordered_list_as_list(self):
        if self.ordered_list:
            return self.ordered_list.splitlines()
        return []

FinalProject/projects/forms.py
from django.forms import ModelForm
from .models import Project, Lesson, LessonSection

# Generate a form to add new Projects to the db based on the current Project model
class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'featured_image','description']

class LessonSectionForm(ModelForm):
    class Meta:
        model = LessonSection
        fields = ['title', 'content', 'ordered_list', 'term_definition', 'image']

class LessonForm(ModelForm):
    class Meta:
        model = Lesson
        fields = ['project', 'title', 'content', 'number'] 

FinalProject/projects/views.py
import os
import chardet
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Project, Lesson
from quizes.models import Quiz
from users.models import Profile
from .forms import ProjectForm, LessonForm, LessonSectionForm
from django.forms import formset_factory
from django.views.decorators.csrf import csrf_exempt



def projects(request):
    projects = Project.objects.all()
    try:
        profile_obj = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile_obj = None
    context = {
        'projects' : projects,
        'profile' : profile_obj,
    }
    return render(request, 'projects/projects.html', context)


def detect_encoding(file_path):
    with open(file_path, 'rb') as file:
        result = chardet.detect(file.read())
        return result['encoding']


def project(request, pk):
    projectObj = Project.objects.get(id=pk)
    lessons = Lesson.objects.filter(project=projectObj).order_by('number').all()
    lessons_ids = list(lessons.values_list('id', flat=True))
    quiz = Quiz.objects.filter(project=projectObj)
    try:
        profile_obj = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile_obj = None
    print("Lessons: ", lessons)
    context = {
        'project':projectObj,
        'lessons':lessons,
        'quiz':quiz,
        'lessons_ids':lessons_ids,
        'profile':profile_obj,
    }
    return render(request, 'projects/single-project.html', context)

@login_required(login_url="login")
def createProject(request):
    form = ProjectForm()
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('projects:projects')
    context = {
        'form':form,
    }
    return render(request, 'projects/project_form.html', context)

@login_required(login_url="login")
def updateProject(request, pk):
    project = Project.objects.get(id=pk)
    form = ProjectForm(instance=project)
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            form.save()
            return redirect('projects:projects')
    context = {
        'form':form,
    }
    return render(request, 'projects/project_form.html', context)

@login_required(login_url="login")
def deleteProject(request, pk):
    project = Project.objects.get(id=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('projects:projects')
    context = {
        'object':project,
    }
    return render(request, 'projects/delete_template.html', context)

@login_required(login_url="login")
def createLesson(request):
    if request.method == 'POST':
        lesson_form = LessonForm(request.POST)
        section_formset = formset_factory(LessonSectionForm, extra=int(request.POST.get('section_count', 1)))(request.POST, request.FILES, prefix='sections')

        if lesson_form.is_valid() and all(form.is_valid() for form in section_formset):
            lesson = lesson_form.save()

            for form in section_formset:
                section = form.save(commit=False)
                section.lesson = lesson
                section.save()

            return redirect('projects:projects')  # Redirect to the project details page or another appropriate page
    else:
        lesson_form = LessonForm()
        section_formset = formset_factory(LessonSectionForm, extra=1)(prefix='sections')

    context = {
        'lesson_form': lesson_form,
        'section_formset': section_formset,
    }

    return render(request, 'projects/create_lesson.html', context)


@csrf_exempt
def update_current_module(request):
    if request.method == 'POST':
        module_title = request.POST.get('module_title', '')
        try:
            profile_obj = Profile.objects.get(user=request.user)
            project = Project.objects.get(title=module_title)
            current_module_number = project.number
            modules_completed = profile_obj.modules_completed
            print("Current_module_number: ", current_module_number)
            print("Modules_completed: ", modules_completed)

            if current_module_number >= modules_completed:
                profile_obj.current_module = module_title
                profile_obj.modules_completed = current_module_number
                print("Current module was just changed in the back end! Changed to: ", profile_obj.current_module)
                print("Modules Completed: ", profile_obj.modules_completed)
                profile_obj.save()
                return JsonResponse({'success': True})
            else:
                print("You already completed that module, just decided to go over it again!")
        except Profile.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Profile not found'})
    return JsonResponse({'success': False, 'error': 'Invalid request'})

FinalProject/projects/templates/projects/create_lesson.html
{% extends 'main.html' %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h2 class="text-center mb-4">Create Lesson for one of the existing Modules</h2>

        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <h5><i>Put descriptive information about the Lesson</i></h5>
          <div class="form-group row">
            <label class="col-md-3 col-form-label">Lesson {{ lesson_form.title.label_tag }}</label>
            <div class="col-md-9">
              {{ lesson_form.title }}
            </div>
          </div>

          <div class="form-group row">
            <label class="col-md-3 col-form-label">{{ lesson_form.content.label_tag }}</label>
            <div class="col-md-9">
              {{ lesson_form.content }}
            </div>
          </div>

          <div class="form-group row">
            <label class="col-md-3 col-form-label">{{ lesson_form.project.label_tag }}</label>
            <div class="col-md-9">
              {{ lesson_form.project }}
            </div>
          </div>

          <div class="form-group row">
            <label class="col-md-3 col-form-label">{{ lesson_form.number.label_tag }}</label>
            <div class="col-md-9">
              {{ lesson_form.number }}
            </div>
          </div>

          {{ section_formset.management_form }}

          <h5><i>Input information about the the Section of a Lesson</i></h5>
          
          {% for form in section_formset %}
            <div class="form-group row">
              <label class="col-md-3 col-form-label">Section {{ form.title.label_tag }}</label>
              <div class="col-md-9">
                {{ form.title }}
              </div>
            </div>

            <div class="form-group row">
              <label class="col-md-3 col-form-label">{{ form.content.label_tag }}</label>
              <div class="col-md-9">
                {{ form.content }}
              </div>
            </div>

            <div class="form-group row">
              <label class="col-md-3 col-form-label">{{ form.ordered_list.label_tag }}</label>
              <div class="col-md-9">
                {{ form.ordered_list }}
              </div>
            </div>

            <div class="form-group row">
              <label class="col-md-3 col-form-label">{{ form.term_definition.label_tag }}</label>
              <div class="col-md-9">
                {{ form.term_definition }}
              </div>
            </div>

            <div class="form-group row">
              <label class="col-md-3 col-form-label">{{ form.image.label_tag }}</label>
              <div class="col-md-9">
                {{ form.image }}
              </div>
            </div>
          {% endfor %}

          <div class="form-group row">
            <div class="col-md-12">
              <input type="submit" class="btn btn-primary btn-block mt-3" value="Create Lesson">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

FinalProject/projects/templates/projects/delete_template.html
{% extends 'main.html' %}
{% block content%}

<form action="" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>
    <a href="{% url 'projects' %}">Go Back</a>
    <input type="submit" value="Confirm"/>
</form>

{% endblock %}

FinalProject/projects/templates/projects/project_form.html
{% extends 'main.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center mb-4">Create new Module for Crypto app</h2>

            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.title.label_tag }}
                    {{ form.title }}
                </div>
                <div class="form-group">
                    {{ form.description.label_tag }}
                    {{ form.description }}
                </div>
                <div class="form-group">
                    {{ form.featured_image.label_tag }}
                    {{ form.featured_image }}
                </div>
                <button type="submit" class="btn btn-primary btn-block mb-2">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

FinalProject/projects/templates/projects/projects.html
{%  extends 'main.html' %}

{%  block content %}

<h1 class="ml-4">Modules</h1>

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 ml-4 mr-4">
    {% for project in projects %}
    <div class="col mb-4">
        <div class="card position-relative">
            <img src="{{ project.featured_image.url }}" class="card-img-top" alt="{{ project.title }}" style="height: 200px; object-fit: cover;">
            <div class="card-body">
                <h5 class="card-title">{{ project.title }}</h5>
                {% if request.user.is_staff %}
                    <a href="{% url 'projects:update-project' project.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'projects:delete-project' project.id %}" class="btn btn-danger">Delete</a>
                {% endif %}
                {% if profile.modules_completed >= forloop.counter0 or user.username == "CryptoAdmin" %}
                    <a href="{% url 'projects:project' project.id %}" class="btn btn-info">View</a>
                {% else %}
                    <button class="btn btn-info" disabled>View</button>
                {% endif %}
                <span class="badge bg-secondary position-absolute bottom-0 end-0 rounded-pill mr-4 mb-3" style="font-size: 1.3rem;">{{ project.number }}</span>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

FinalProject/projects/templates/projects/single-project.html
{% extends 'main.html' %}

{% load static %}

{% block content %}
<style>
  
  ::-webkit-scrollbar {
      width: 0.7vw;
  }

  ::-webkit-scrollbar-thumb {
      background-color: #0d6efd;
      border-radius: 3px;
  }

  ::-webkit-scrollbar-thumb:hover {
      background-color: #0d56c3;
  }
</style>

  <div class="container mt-4">
    <div class="row">
      <div class="col-lg-6 mb-4">
        <img class="img-fluid" src="{{ project.featured_image.url }}" alt="{{ project.title }}">
      </div>
      <div class="col-lg-6">
        <h1>{{ project.title }}</h1>
        <hr>
        <p>{{ project.description }}</p>
        <!-- Add Start Lesson button here -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#lessonModal{{ lessons.0.number }}">Start with <i>{{ lessons.0.title }}</i></button>
        <!-- Add Take Quiz button here -->
        {% if quiz.0 %}
          {% if profile.current_module == project.title or user.username == "CryptoAdmin"%}
            <a href="{% url 'quizes:quiz-view' quiz.0.id %}" class="btn btn-danger" id="quizButton">Take <i>{{quiz.0.name}}</i></a>
          {% else %}
            <a href="{% url 'quizes:quiz-view' quiz.0.id %}" class="btn btn-danger disabled" id="quizButton">Take <i>{{quiz.0.name}}</i></a>
          {% endif %}
        {% endif %}
      </div>
    </div>

    <!-- Lesson Modal for the selected lesson -->
    {% for lesson in lessons %}
    
    <div class="modal fade" id="lessonModal{{ lesson.number }}" tabindex="-1" aria-labelledby="lessonModalLabel{{ lesson.id }}" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="lessonModalLabel{{ lesson.number }}">{{ lesson.title }}</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body" style="overflow: scroll">
                  {% if lesson.content %}
                    {{lesson.content}}
                  {% endif %}
                  {% for section in lesson.sections.all %}
                      <h5>{{ section.title }}</h5>
                      <p>{{ section.content }}</p>
                      <img src="{{ section.image.url }}" alt="Lesson Image" style="width: 100%">
                      {% if section.ordered_list %}
                        <ol>
                            {% for item in section.get_ordered_list_as_list %}
                                <li>{{ item }}</li>
                            {% endfor %}
                        </ol>
                      {% endif %}
                      {% if section.term_definition %}
                        <div style="border: 1px solid #ccc; padding: 10px; margin: 10px 0;">
                          {{ section.term_definition }}
                        </div>
                      {% endif %}
                  {% endfor %}
              </div>
              <div class="modal-footer">
                {% if forloop.first %}
                      <!-- First lesson, show Next button -->
                      <button type="button" class="btn btn-primary" data-bs-target="#lessonModal{{ lesson.number|add:1 }}" data-bs-toggle="modal" data-bs-dismiss="modal">Next</button>
                  {% elif forloop.last %}
                      <!-- Last lesson, show Previous button -->
                      <button type="button" class="btn btn-secondary" data-bs-target="#lessonModal{{ lessons.first.id }}" data-bs-toggle="modal" data-bs-dismiss="modal">Previous</button>
                      <button type="button" class="btn btn-danger" data-bs-dismiss="modal" onclick="markLessonAsCompleted()">Close</button>
                  {% else %}
                      <!-- In between lessons, show both Next and Previous buttons -->
                      <button type="button" class="btn btn-secondary" data-bs-target="#lessonModal{{ lesson.number|add:-1}}" data-bs-toggle="modal" data-bs-dismiss="modal">Previous</button>
                      <button type="button" class="btn btn-primary" data-bs-target="#lessonModal{{ lesson.number|add:1 }}" data-bs-toggle="modal" data-bs-dismiss="modal">Next</button>
                  {% endif %}
              </div>
          </div>
      </div>
  </div>
  {% endfor %}
  </div>
  <script>
    // Variable indicating whether the user has completed the lesson
    var userCompletedLesson = false;
    // Function to enable the quiz button if the user has completed the lesson
    function enableQuizButton() {
      if (userCompletedLesson) {
        document.getElementById('quizButton').disabled = false;
      }
    }
  
    // Call enableQuizButton function when the "Close" button is pressed
    $('#lessonModal{{ lessons.last.id }} .btn-danger').on('click', function () {
      // Assuming you have a variable indicating the current lesson title
      
      console.log("Project title sending to the backend: ", project.title)
      enableQuizButton();
      markLessonAsCompleted(moduleTitle);
    });

    // Get the CSRF token from the cookie
    var csrftoken = getCookie('csrftoken');
 

    // You should set userCompletedLesson to true when the user completes the lesson
    function markLessonAsCompleted() {
      userCompletedLesson = true;
      var moduleTitle = '{{ project.title }}';
      document.getElementById('quizButton').classList.remove('disabled');
      // Update the current_module field in the user's profile
      $.ajax({
        type: 'POST',
        url:  "http://127.0.0.1:8000/lessons/update_current_module/",  // Replace with the actual URL for updating the current module
        data: { module_title: moduleTitle },
        headers: {'X-CSRFToken': csrftoken},
        success: function (data) {
          console.log('Current module updated successfully');
        },
        error: function (error) {
          console.error('Error updating current module:', error);
        }
      });

      // Function to get the CSRF token from the cookie
      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
    }
  </script>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

{% endblock content %}